# Generated by Django 4.2.3 on 2023-07-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapplication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="moddate",
            field=models.DateTimeField(null=True),
        ),
    ]
