# Generated by Django 4.2.3 on 2023-07-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web0726", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="itemname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="item",
            name="pictureurl",
            field=models.CharField(max_length=100),
        ),
    ]
